// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: beewatch.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriberClient is the client API for Subscriber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriberClient interface {
	ReceiveEvents(ctx context.Context, opts ...grpc.CallOption) (Subscriber_ReceiveEventsClient, error)
}

type subscriberClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberClient(cc grpc.ClientConnInterface) SubscriberClient {
	return &subscriberClient{cc}
}

func (c *subscriberClient) ReceiveEvents(ctx context.Context, opts ...grpc.CallOption) (Subscriber_ReceiveEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Subscriber_ServiceDesc.Streams[0], "/beewatch.api.v1.Subscriber/ReceiveEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriberReceiveEventsClient{stream}
	return x, nil
}

type Subscriber_ReceiveEventsClient interface {
	Send(*Event) error
	Recv() (*Control, error)
	grpc.ClientStream
}

type subscriberReceiveEventsClient struct {
	grpc.ClientStream
}

func (x *subscriberReceiveEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *subscriberReceiveEventsClient) Recv() (*Control, error) {
	m := new(Control)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriberServer is the server API for Subscriber service.
// All implementations must embed UnimplementedSubscriberServer
// for forward compatibility
type SubscriberServer interface {
	ReceiveEvents(Subscriber_ReceiveEventsServer) error
	mustEmbedUnimplementedSubscriberServer()
}

// UnimplementedSubscriberServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriberServer struct {
}

func (UnimplementedSubscriberServer) ReceiveEvents(Subscriber_ReceiveEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveEvents not implemented")
}
func (UnimplementedSubscriberServer) mustEmbedUnimplementedSubscriberServer() {}

// UnsafeSubscriberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberServer will
// result in compilation errors.
type UnsafeSubscriberServer interface {
	mustEmbedUnimplementedSubscriberServer()
}

func RegisterSubscriberServer(s grpc.ServiceRegistrar, srv SubscriberServer) {
	s.RegisterService(&Subscriber_ServiceDesc, srv)
}

func _Subscriber_ReceiveEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SubscriberServer).ReceiveEvents(&subscriberReceiveEventsServer{stream})
}

type Subscriber_ReceiveEventsServer interface {
	Send(*Control) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type subscriberReceiveEventsServer struct {
	grpc.ServerStream
}

func (x *subscriberReceiveEventsServer) Send(m *Control) error {
	return x.ServerStream.SendMsg(m)
}

func (x *subscriberReceiveEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Subscriber_ServiceDesc is the grpc.ServiceDesc for Subscriber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscriber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beewatch.api.v1.Subscriber",
	HandlerType: (*SubscriberServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveEvents",
			Handler:       _Subscriber_ReceiveEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "beewatch.proto",
}
